// Generated by CoffeeScript 1.12.4
var View, methods, render;

View = require("modx/lib/View");

module.exports = function(type) {
  type.render(render);
  return type.defineMethods(methods);
};

render = function() {
  var touchHandlers, viewProps;
  touchHandlers = this._tap.join(this._hold).touchHandlers;
  viewProps = View.parseProps(this.props);
  return View({
    children: this.__renderChildren(),
    mixins: [viewProps, touchHandlers],
    style: [
      {
        flexDirection: "row"
      }, this.props.style
    ]
  });
};

methods = {
  __renderChildren: function() {
    return this.props.children || [this.__renderIcon(), this.__renderText()];
  }
};
